artifact_location: file:///c:/Users/lenevo/Desktop/project_mlflow/mlflow_demo/mlruns/241491399312701581
creation_time: 1775121340019
experiment_id: '241491399312701581'
last_update_time: 1775121340019
lifecycle_stage: active
name: diabetes_xgboost
workspace: default
